version: 0.2

phases:
  pre_build:
    commands:
      - echo Install packages...
      - npm install
      - npx prisma migrate dev
  build:
    commands:
      - echo Create build ...
      - npm run build
  post_build:
    commands:
      - echo Removing unnecessary files...
      - rm -rf node_modules/
artifacts:
  base-directory: '.'
  files:
    - '**/*'  
env:
  variables:
    DATABASE_URL: "postgresql://assuexadm:H6ADBBxFiC1G$DCn@assuexdb.czqsacyr07b9.us-east-1.rds.amazonaws.com"
